
<Menuwidget>:
    canvas.before:
        Color:
            rgba: 0 , 0, 0, .8
        Rectangle:
            size: self.size
    Label:
        font_size:dp(65)
        text:root.parent.menu_ti
        pos_hint: {"center_x":0.5,"center_y":0.6}
    Button:
        font_size:dp(32)

        text:root.parent.menu_buttonti
        pos_hint: {"center_x":0.5,"center_y":0.3}
        size_hint:0.2,0.15
        on_press:root.parent.onbuttonpressed()
        background_color:1,.3,.4,.85